[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
whitelist_gated_token_sale = "GkvBG6cxfEBnuSvb2Zk5tA2qb3aPWWL3doj43dUKHf23"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
